In [1]:
# 模型來源
# https://fasttext.cc/docs/en/supervised-models.html#content

# 測試資料 bauhouse hotel-data

In [1]:
import fasttext
from pyfasttext import FastText
import time

# 遇到錯誤
### Cannot load amazon_review_full.bin due to C++ extension failed to allocate the memory
###  目前已知解決不了的原因之一不是因為記憶體不足（已經調高至8GB）
###  如果用pyfasttext 就可以解決這問題
###  如果是載入自己訓練的模型也可以

In [2]:
amazon_model = fasttext.load_model('./model/amazon_review_polarity.bin' )
# amazon_model = fasttext.load_model('amazon_review_full.bim')

#遇到錯誤 Cannot load amazon_review_full.bin due to C++ extension failed to allocate the memory

Exception: fastText: Cannot load ./model/amazon_review_polarity.bin due to C++ extension failed to allocate the memory

## 果然可以載入自己訓練的模型
### 有沒有可能是記憶體需求較小問題? 要再查證

In [3]:
own_model = fasttext.load_model('./model/skip_model.bin' )

# 改用pyfasttext 載入模型  問題解決

In [4]:
# 改用pyfasttext載入模型
from pyfasttext import FastText 

## 載入模型寫法1

In [5]:
# 可以載入
# 這個模型簡單分為2類
amazon_model = FastText('./model/amazon_review_polarity.bin')

# 以下的模型有更多的分類 暫時不用
# amazon_model = FastText('amazon_review_full.bin')

## 載入模型寫法2

In [4]:
amazon_model = FastText()

In [5]:
amazon_model.load_model('./model/amazon_review_polarity.bin' )

In [6]:
#看單字向量
amazon_model.get_numpy_text_vector('good')

array([ 0.01543132,  0.00838315,  0.13463734,  0.14711222,  0.01659458,
       -0.10773403,  0.01058692,  0.28777453, -0.07692628, -0.15495609],
      dtype=float32)

In [7]:
# 幾種單字
amazon_model.nwords

1566402

In [8]:
# 獲得詞向量
amazon_model.get_numpy_vector('nice')

array([-0.02588347,  0.00742587,  0.00842597,  0.21571034, -0.05824237,
       -0.10667482,  0.03962445,  0.27596688,  0.03156604, -0.2427172 ],
      dtype=float32)

In [9]:
# 獲得句子向量
amazon_model.get_numpy_sentence_vector('service was good')

array([ 1.18041635e-01,  9.44949389e-02,  5.94291016e-02,  2.02926129e-01,
        1.30660832e-04, -5.36133572e-02, -6.62512854e-02,  2.15543918e-02,
       -2.90704034e-02,  1.44479871e-01], dtype=float32)

# 1 = 負向 ,  2 = 正向  

In [10]:
# 看是正向還是負向
amazon_model.predict(["I like it"])

[['2']]

In [11]:
amazon_model.predict(["I don`t like it"])

[['1']]

In [12]:
# 看是那一個面向的機率有多少
amazon_model.predict_proba(["I like it"])

[[('2', 0.9980468749261779)]]

In [13]:
# 看是那一個面向的機率有多少
amazon_model.predict_proba(["I don't like it"],2)

[[('2', 0.9843749995745935), ('1', 0.013671891970546681)]]

# 準確率不錯高

In [14]:
texts = [ 'example very longtext so I think that is not suitable'
        ,'Washington Posts Attack Article on Google Duplex made me throw Alexa in the trash!'
        ,'good nice well done'] 

In [15]:
labels = amazon_model.predict(texts)

In [16]:
print (labels)

[['1'], ['1'], ['2']]
