In [2]:
import numpy as np 
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
import re

Using TensorFlow backend.


In [3]:
data=pd.read_csv('包浩斯資料集(test).csv',engine='python')
#data = data[['text','score']]

In [4]:
data

text  score  overall
0     This was my second stay at the Hotel Pulitzer....      2        1
1     this hotel is truely the best in amsterdam and...      5        3
2     Just spent 3 nights at this hotel 5th March 04...      4        3
3     I had communicated 6 months in advance, reques...      2        1
4     We stayed in this hotel 3 nights with my wife ...      1        1
5     Got a great rate for this hotel on hotwire ($1...      4        3
6     in short, this is an OK 3 or 4 star hotel. but...      2        1
7     a five star rat in my room ! Don't get fool by...      1        1
8     The Hotel's location is brilliant, and within ...      2        1
9     I stayed at the Hotel Pulitzer in the beginnin...      5        3
10    This hotel was just a great disappointment.The...      2        1
11    Having booked a deluxe room at the Pulitzer, w...      1        1
12    The hotel itself lies along a grand canal in a...      5        3
13    I have stayed here twice recently and have to ...      1        1
14    Stayed here for 3 nights in May 08, in an exec...      2        1
15    We were planning to stay at this hotel but our...      1        1
16    I stayed at the hotel during my first trip to ...      5        3
17    So on first impression, all looked ok. Room wa...      1        1
18    We had made a very early fully refundable rese...      1        1
19    I am shocked by the other reviews. I travel fo...      1        1
20    Hugely disappointed. Reserved this hotel b/c i...      2        1
21    After much research, I finally decided on this...      2        1
22    My family and I had a nice and trouble free 4 ...      4        3
23    I definitely agree with other reviewers who wr...      2        1
24    We stayed at the Pulitzer some time ago (Augus...      4        3
25    Non-existent service, poor food, rude attitude...      2        1
26    You will have read from other irrate clients t...      2        1
27    I just read some of the bad reviews for the Pu...      1        1
28    My husband and I thought this hotel was "centr...      4        3
29    We were traveling with a group of 5 couples an...      5        3
...                                                 ...    ...      ...
1649  I happened to stay at this boutique hotel in s...      4        3
1650  The Altamont is a fantastic boutique hotel, in...      5        3
1651  I satyed at the Altamont for seven nights. I t...      2        1
1652  I stayed here during the end of September/star...      2        1
1653  "Luxury"? Five stars? Have we stayed at the sa...      1        1
1654  The hotel is very charming but the service is ...      2        1
1655  Stayed for 2 nights in corner suite. Arrived a...      1        1
1656  Stayed 6 nights at the Amora from 27 November ...      4        3
1657  Nice rooms, comfortable beds, and very friendl...      5        3
1658  I booked our stay via Expedia from the Uk base...      5        3
1659  The facilities, if they were OPEN, would have ...      1        1
1660  stayed 31/12/06 until 3/1/07.never again will ...      1        1
1661  The house keeping was very bad.The staff in th...      1        1
1662  My husband and I stayed at the Amora Jamison f...      1        1
1663  Booked this hotel from the internet and everyt...      1        1
1664  Poor check-in, unfriendly staff, didn't clean ...      1        1
1665  I think we first stayed at this hotel in Decem...      4        3
1666  About a month ago I booked two Jamison Club ro...      2        1
1667  We arrived in Sydney on short notice and being...      2        1
1668  It is an anomaly that this hotel is rated so h...      2        1
1669  uk trip advisor member. We spent 5 nights here...      2        1
1670  I spent 1 night at the Amora when on Business....      4        3
1671  This hotel was VERY dissapointing. Firstly we ...      2        1
1672  Our room was big and has a great bathroom - ab...      5        3
1673  I had a mixed

In [5]:
data['text'] = data['text'].apply(lambda x: x.lower())
data['text'] = data['text'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))

In [6]:
data['text']

0       this was my second stay at the hotel pulitzer ...
1       this hotel is truely the best in amsterdam and...
2       just spent 3 nights at this hotel 5th march 04...
3       i had communicated 6 months in advance request...
4       we stayed in this hotel 3 nights with my wife ...
5       got a great rate for this hotel on hotwire 195...
6       in short this is an ok 3 or 4 star hotel but f...
7       a five star rat in my room  dont get fool by b...
8       the hotels location is brilliant and within wa...
9       i stayed at the hotel pulitzer in the beginnin...
10      this hotel was just a great disappointmentthe ...
11      having booked a deluxe room at the pulitzer we...
12      the hotel itself lies along a grand canal in a...
13      i have stayed here twice recently and have to ...
14      stayed here for 3 nights in may 08 in an execu...
15      we were planning to stay at this hotel but our...
16      i stayed at the hotel during my first trip to ...
17      so on 

In [7]:
max_fatures = 20000
tokenizer = Tokenizer(num_words=max_fatures, split=' ')
tokenizer.fit_on_texts(data['text'].values)

In [8]:
X = tokenizer.texts_to_sequences(data['text'].values)

In [9]:
X[100]

[51,
 12,
 7654,
 10,
 405,
 5,
 730,
 3332,
 23,
 1028,
 40,
 248,
 76,
 3,
 7655,
 543,
 7656,
 8,
 83,
 507,
 646,
 39,
 20,
 37,
 15,
 114,
 6,
 1751,
 802,
 4,
 448,
 48,
 133,
 4405,
 147,
 58,
 169,
 597,
 59,
 3789,
 8,
 5433,
 1887,
 167,
 6,
 27,
 534,
 7657,
 171,
 1997,
 4,
 187,
 1,
 349,
 9,
 54,
 52,
 42,
 55,
 2,
 205,
 51,
 5,
 48,
 479,
 38,
 78,
 77]

In [10]:
X = pad_sequences(X,500)

In [11]:
X

array([[   0,    0,    0, ...,  338,    1,  152],
       [   0,    0,    0, ...,    4,  299, 2326],
       [   0,    0,    0, ...,    1,  277,   94],
       ..., 
       [   0,    0,    0, ...,  745,   32,   46],
       [   0,    0,    0, ...,  267,  168, 2992],
       [   0,    0,    0, ...,    4,  682,  443]])

In [16]:
Y = pd.get_dummies(data['overall']).values

In [17]:
Y

array([[1, 0],
       [0, 1],
       [0, 1],
       ..., 
       [0, 1],
       [0, 1],
       [1, 0]], dtype=uint8)

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.33, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(1124, 500) (1124, 2)
(555, 500) (555, 2)


# LSTM

In [19]:
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from keras import metrics

In [20]:
# fix random seed for reproducibility
numpy.random.seed(7)
# load the dataset but only keep the top n words, zero the rest
top_words = 20000


# create the model
embedding_vecor_length = 128
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=X.shape[1], dropout=0.2))
model.add(LSTM(100))
model.add(Dense(2, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=[metrics.categorical_accuracy])
print(model.summary())
model.fit(X_train, Y_train, epochs=10, batch_size=64)
# Final evaluation of the model
scores = model.evaluate(X_test, Y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

C:\Users\JEFF\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  # Remove the CWD from sys.path while we load stuff.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 500, 128)          2560000   
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               91600     
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 202       
Total params: 2,651,802
Trainable params: 2,651,802
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
1124/1124 [==============================] - 20s - loss: 0.6862 - categorical_accuracy: 0.5890    
Epoch 2/10
1124/1124 [==============================] - 19s - loss: 0.4892 - categorical_accuracy: 0.7856    
Epoch 3/10
1124/1124 [==============================] - 18s - loss: 0.3573 - categorical_accuracy: 0.9021    
Epoch 4/10
1124/1124 [==============================] - 19s -

In [21]:
# sklearn

In [22]:
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

In [38]:
out = model.predict_proba(X_test)
out = np.array(out)
out

555/555 [==============================] - 3s     


array([[  1.86323689e-03,   9.98136759e-01],
       [  6.24107659e-01,   3.75892341e-01],
       [  9.94319260e-01,   5.68081439e-03],
       ..., 
       [  9.99938846e-01,   6.12020231e-05],
       [  9.92574096e-01,   7.42586609e-03],
       [  9.99726117e-01,   2.73873331e-04]], dtype=float32)

In [39]:
threshold = np.arange(0.1,0.9,0.1)

acc = []
accuracies = []
best_threshold = np.zeros(out.shape[1])
for i in range(out.shape[1]):
    y_prob = np.array(out[:,i])
    for j in threshold:
        y_pred = [1 if prob>=j else 0 for prob in y_prob]
        acc.append( matthews_corrcoef(Y_test[:,i],y_pred))
    acc   = np.array(acc)
    index = np.where(acc==acc.max()) 
    accuracies.append(acc.max()) 
    best_threshold[i] = threshold[index[0][0]]
    acc = []

In [40]:
best_threshold

array([ 0.7,  0.1])

In [41]:
y_pred = np.array([[1 if out[i,j]>=best_threshold[j] else 0 for j in range(Y_test.shape[1])] for i in range(len(Y_test))])
y_pred

array([[0, 1],
       [0, 1],
       [1, 0],
       ..., 
       [1, 0],
       [1, 0],
       [1, 0]])

In [27]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, y_pred))

             precision    recall  f1-score   support

          0       0.87      0.75      0.81       290
          1       0.76      0.88      0.82       265

avg / total       0.82      0.81      0.81       555



# CNN

In [28]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Convolution1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers.embeddings import Embedding
from keras.layers.core import Dense, Dropout, Activation
from keras import metrics
#from keras.preprocessing import sequence

In [29]:
model = Sequential()
model.add(Embedding(20000,input_length=X.shape[1], output_dim = 128))

model.add(Convolution1D(activation="relu", filters=250, kernel_size=3, strides=1, padding="valid"))
model.add(MaxPooling1D(pool_size = 2))
model.add(Flatten())
model.add(Dense(250)) 
model.add(Dropout(0.2)) 
model.add(Activation('relu'))
model.add(Dense(2))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam', metrics= [ metrics.categorical_accuracy  ])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 500, 128)          2560000   
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 498, 250)          96250     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 249, 250)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 62250)             0         
_________________________________________________________________
dense_2 (Dense)              (None, 250)               15562750  
_________________________________________________________________
dropout_1 (Dropout)          (None, 250)               0         
_________________________________________________________________
activation_1 (Activation)    (None, 250)               0         
__________

In [30]:
hist=model.fit(X_train, Y_train, batch_size= 32, epochs=10, validation_split=0.1)

Train on 1011 samples, validate on 113 samples
Epoch 1/10
1011/1011 [==============================] - 18s - loss: 0.7091 - categorical_accuracy: 0.5648 - val_loss: 0.6152 - val_categorical_accuracy: 0.6549
Epoch 2/10
1011/1011 [==============================] - 16s - loss: 0.3393 - categorical_accuracy: 0.8546 - val_loss: 0.3331 - val_categorical_accuracy: 0.8496
Epoch 3/10
1011/1011 [==============================] - 14s - loss: 0.0675 - categorical_accuracy: 0.9782 - val_loss: 0.4415 - val_categorical_accuracy: 0.8673
Epoch 4/10
1011/1011 [==============================] - 17s - loss: 0.0145 - categorical_accuracy: 0.9990 - val_loss: 0.3888 - val_categorical_accuracy: 0.8761
Epoch 5/10
1011/1011 [==============================] - 16s - loss: 0.0025 - categorical_accuracy: 1.0000 - val_loss: 0.3586 - val_categorical_accuracy: 0.8850
Epoch 6/10
1011/1011 [==============================] - 16s - loss: 0.0012 - categorical_accuracy: 1.0000 - val_loss: 0.3684 - val_categorical_accuracy: 

In [24]:
hist=model.fit(X_train, Y_train, epochs=10, batch_size=32)

Epoch 1/10
1124/1124 [==============================] - 16s - loss: 0.0583 - categorical_accuracy: 0.9840    
Epoch 2/10
1124/1124 [==============================] - 15s - loss: 0.0096 - categorical_accuracy: 0.9991    
Epoch 3/10
1124/1124 [==============================] - 15s - loss: 7.8790e-04 - categorical_accuracy: 1.0000    
Epoch 4/10
1124/1124 [==============================] - 15s - loss: 2.3712e-04 - categorical_accuracy: 1.0000    
Epoch 5/10
1124/1124 [==============================] - 15s - loss: 1.6184e-04 - categorical_accuracy: 1.0000    
Epoch 6/10
1124/1124 [==============================] - 15s - loss: 1.0161e-04 - categorical_accuracy: 1.0000    
Epoch 7/10
1124/1124 [==============================] - 15s - loss: 7.0791e-05 - categorical_accuracy: 1.0000    
Epoch 8/10
1124/1124 [==============================] - 15s - loss: 7.4234e-05 - categorical_accuracy: 1.0000    
Epoch 9/10
1124/1124 [==============================] - 15s - loss: 6.1175e-05 - categorical_acc

In [31]:
score, acc = model.evaluate(X_test, Y_test, batch_size= 64)
print('Test score:', score)
print('Test accuracy:', acc)

555/555 [==============================] - 1s     
Test score: 0.438291463229
Test accuracy: 0.882882881487


In [36]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, y_pred))

             precision    recall  f1-score   support

          0       0.89      0.90      0.90       290
          1       0.89      0.88      0.88       265

avg / total       0.89      0.89      0.89       555



# CNN+LSTM

In [37]:
# LSTM and CNN for sequence classification in the IMDB dataset
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.convolutional import Convolution1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
# fix random seed for reproducibility
numpy.random.seed(7)
# load the dataset but only keep the top n words, zero the rest
top_words = 20000

# create the model
model = Sequential()
model.add(Embedding(top_words, 256, input_length=X.shape[1]))
#model.add(Convolution1D(nb_filter=32, filter_length=3, border_mode='same', activation='softmax'))
model.add(Convolution1D(activation="relu", filters=250, kernel_size=3, strides=1, padding="valid"))
model.add(MaxPooling1D(pool_length=2))
model.add(LSTM(100))
model.add(Dense(2, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=[metrics.categorical_accuracy])
print(model.summary())
model.fit(X_train, Y_train, epochs=10, batch_size=64)
# Final evaluation of the model
scores = model.evaluate(X_test, Y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

C:\Users\JEFF\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(pool_size=2)`


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 500, 256)          5120000   
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 498, 250)          192250    
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 249, 250)          0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               140400    
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 202       
Total params: 5,452,852
Trainable params: 5,452,852
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
1124/1124 [==============================] - 24s - loss: 0.6825 - categorical_accuracy: 0.5552    
Epoch 2/10
1124/1

In [42]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, y_pred))

             precision    recall  f1-score   support

          0       0.87      0.89      0.88       290
          1       0.87      0.87      0.87       265

avg / total       0.87      0.88      0.87       555

