In [ ]:
# 模型來源
# https://fasttext.cc/docs/en/supervised-models.html#content

In [ ]:
# 測試資料集使用bauhouse -hotel data

In [1]:
import fasttext
from pyfasttext import FastText
import time

# 載入ftz模型 容量較小

In [2]:
amazon_model = FastText('./model/amazon_review_polarity.ftz')

In [3]:
# 看使用的參數
amazon_model.args

{'bucket': 10000000,
 'cutoff': 0,
 'dim': 10,
 'dsub': 2,
 'epoch': 5,
 'input': '',
 'label': '__label__',
 'loss': 'softmax',
 'lr': 0.05,
 'lrUpdateRate': 100,
 'maxn': 0,
 'minCount': 1,
 'minCountLabel': 0,
 'minn': 0,
 'model': 'supervised',
 'neg': 5,
 'output': '',
 'pretrainedVectors': '',
 'qnorm': False,
 'qout': False,
 'retrain': False,
 'saveOutput': 0,
 't': 0.0001,
 'test': '',
 'thread': 12,
 'verbose': 2,
 'wordNgrams': 2,
 'ws': 5}

In [4]:
#看單字向量
# 與.bin檔案向量不同
amazon_model.get_numpy_text_vector('good')

array([ 0.1086161 ,  0.18366042, -0.09068532, -0.20171444, -0.00192232,
       -0.19231492,  0.06512891,  0.62658197, -0.04950603, -0.21930756],
      dtype=float32)

In [5]:
# 幾種單字
amazon_model.nwords

17530

In [ ]:
# amazon_review_polarity.ftz
# 1566402 種單字
# ftz 容量小 但是單字也少很多

In [6]:
# 獲得詞向量
amazon_model.get_numpy_vector('nice')

array([-0.01576342,  0.03520598, -0.01807051,  0.18462387, -0.09142927,
       -0.15884861,  0.04484949,  0.37294215,  0.03853114, -0.27779093],
      dtype=float32)

In [7]:
# 獲得句子向量
amazon_model.get_numpy_sentence_vector('service was good')

array([ 0.03510009, -0.0186391 ,  0.0879257 ,  0.05920646,  0.02545856,
       -0.18054652, -0.06264028,  0.35118797, -0.06852235,  0.2444516 ],
      dtype=float32)

# 1 = 負向 , 2 = 正向

In [8]:
# 看是正向還是負向
amazon_model.predict(["I like it"])

[['2']]

In [9]:
amazon_model.predict(["I don`t like it"])

[['1']]

In [10]:
# 看是那一個面向的機率有多少
amazon_model.predict_proba(["I like it"])

[[('2', 0.9980468749261779)]]

In [11]:
# 看是那一個面向的機率有多少
amazon_model.predict_proba(["I don't like it"],2)

[[('2', 0.9980468749261779), ('1', 1.9531265169053625e-08)]]

# 把FB模型拿來預測全部資料集

In [12]:
# 這個資料集連label都沒有  只有內容  所以可以拿來預測結果
pred_data = amazon_model.predict_file('./data/hotel_label_clean_onlycontent1.txt')

In [13]:
# 會得到全部資料的預測面向
pred_data

[['1'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['2'],
 ['2'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['2'],
 ['2'],
 ['1'],
 ['2'],
 ['1'],
 ['2'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['2'],
 ['2'],
 ['2'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['2'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['2'],
 ['2'],
 ['2'],
 ['2'],
 ['2'],
 ['2'],
 ['1'],
 ['2'],
 ['1'],
 ['2'],
 ['2'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['2'],
 ['2'],
 ['1'],
 ['1'],
 ['2'],
 ['2'],
 ['2'],
 ['2'],
 ['2'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],
 ['1'],
 ['1'],
 ['2'],
 ['1'],


# 觀看預測的資料集

In [15]:
# 預測後共多少筆資料
len(pred_data)

24033

In [17]:
# 前10筆預測面向
pred_data[0:10]

[['1'], ['1'], ['1'], ['1'], ['2'], ['1'], ['1'], ['2'], ['2'], ['1']]

In [18]:
#  最後一筆資料
pred_data[-1]

['1']

In [19]:
# 為list型態  
type(pred_data[0])

list

# 因為是list型態 必須轉型為str

In [20]:
pred_data_str = []

In [21]:
# 轉換完str丟進去陣列
for i in range(len(pred_data)):
    pred_data_str += list(map(str, pred_data[i]))

In [22]:
# 確認轉換完後 資料筆數正確
len(pred_data_str)

24033

In [23]:
# 觀看型態
type(pred_data_str)

list

In [24]:
# 確定轉換為str
type(pred_data_str[0])

str

In [25]:
# 前10筆預測面向
pred_data_str[0:10]

['1', '1', '1', '1', '2', '1', '1', '2', '2', '1']

In [26]:
# 最後一筆
pred_data_str[-1]

'1'

# 接下來載入正確的資料集(全部的資料集)

In [27]:
import pandas as pd

In [28]:
# hotel_nolabel_clean1.csv
# 為全部的資料集  但是沒有加上_label__ 這樣才可以拿來做迴圈比較
true_data = pd.read_csv('./data/hotel_nolabel_clean1.csv',encoding='utf8' , header =None)

In [30]:
true_data.head(15)

0                                                  1
0   1  my daughter and i just returned from a four ni...
1   1                                     big mistake . 
2   1                                 our room was tiny 
3   1                      and the bath was small too . 
4   1  the public areas were somewhat dingy and showe...
5   1  even the bath towels were worn and becoming st...
6   1  speaking of such  the maid did not replace sha...
7   1  you had to put a sign on the bed if you wanted...
8   1  the minibar was one of the kind that you have ...
9   1  there was a charge of about $5 . 00 to access ...
10  2                the front desk staff were pleasant 
11  1  but the concierges seemed about to scream if o...
12  2  the breakfast buffet was fine  if it is includ...
13  1  otherwise for 20 euros  you could do much bett...
14  2  the location of the pulitzer is excellent  and...

In [31]:
#   共多少筆真實資料
len(true_data)

24033

In [32]:
#int 型態
type(true_data[0][0])

numpy.int64

In [33]:
# 第1筆資料  
(true_data[0][0])

1

In [35]:
# 最後一筆
true_data[0][len(true_data)-1]

2

In [36]:
# 看資料有幾筆
len(true_data)

24033

# 把numpy.int64 轉 str

In [37]:
true_data_str = []

In [38]:
# 把numpy.int64 轉 str 
for i in range(len(true_data)):
    true_data_str += [true_data[0][i].astype(str)]

In [39]:
# 看前15筆
for j in range(15):
    print(true_data_str[j][0])

1
1
1
1
1
1
1
1
1
1
2
1
2
1
2


In [40]:
# 確認轉成str
type(true_data_str[0][0])

str

# 使用 confusion_matrix 誤差計算(混淆矩陣)

In [41]:
from sklearn.metrics import confusion_matrix

/opt/conda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [43]:
confusion_matrix (pred_data_str, true_data_str)

array([[9124, 2716],
       [3386, 8807]])

# 觀看混淆矩陣結果

In [44]:
from sklearn.metrics import classification_report

In [45]:
# avg = ( precision *support ) / total   =  ( 0.78 *12725 + 0.75 *11308 ) /24033
# 1面向跟2面向 分別命中率


# recall = 命中產品項目數/ 目標顧客所想要的產品項目數
# F1−measure = 2 ∗ 𝑃𝑟𝑒𝑐𝑖𝑠𝑖𝑜𝑛 ∗ 𝑅𝑒𝑐𝑎𝑙𝑙( 𝑃𝑟𝑒𝑐𝑖𝑠𝑖𝑜𝑛 + 𝑅𝑒𝑐𝑎𝑙𝑙 )


print( classification_report ( pred_data_str, true_data_str) )

             precision    recall  f1-score   support

          1       0.73      0.77      0.75     11840
          2       0.76      0.72      0.74     12193

avg / total       0.75      0.75      0.75     24033



# 測試結果比amazon_review_polarity.bin檔 準確率低2%